server:
  servlet:
    context-path: /Vilki_Palki_Api
  port: 7576

spring:
  application:
    name: Vilki-Palki
  datasource:
    url: jdbc:postgresql://localhost:5432/avada_slj_vp
    username: avada_slj_vp
    password: mgBOTd2tBb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    username: test.in.odessa@gmail.com
    password: sggcjhmrombnkscg
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp

app:
  jwt:
    secret: SV9ET04nVF9LTk9XX1RIRV9TRUNSRVRfVE9LRU4=
